name: Data Pipeline

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures full Git history is checked out

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Configure DVC
        run: |
          dvc remote add -f origin s3://dvc
          dvc remote modify origin endpointurl https://dagshub.com/lanaben/MBajk-prediction-app.s3
          dvc remote modify origin --local access_key_id 7ddc36c3f8a57b0df9f619f50e6f0a2cf6da5f55 
          dvc remote modify origin --local secret_access_key 7ddc36c3f8a57b0df9f619f50e6f0a2cf6da5f55 

  process_data:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install -r requirements.txt
          pip install dvc

      - name: Pull data with DVC
        run: dvc pull -r origin --force

      - name: Run Python script to generate/update data
        run: python src/data/fetch_weather_data.py

      - name: Add and commit data to DVC
        run: |
          dvc add data
          dvc push -r origin
          git config --global user.name 'lanaben'
          git config --global user.email 'lanaben@users.noreply.github.com'
          git add data.dvc
          git commit -m "Update weather data."
          git push

      - name: Clean up
        run: |
          echo "Data processing completed and changes pushed."



