name: Data Pipeline

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  check_permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List directory structure
        run: |
          pwd
          ls -R

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install DVC
        run: |
          pip install dvc
          dvc --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

  fetch_bike_data:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install DVC
        run: |
          pip install dvc
          dvc --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

      - name: Fetch bike data
        run: python src/data/fetch_bike_data.py
      - name: Cache bike data
        run: dvc add data/raw

  preprocess_bike_data:
    needs: fetch_bike_data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Preprocess bike data
        run: python src/data/process_bike_data.py
      - name: Cache preprocessed bike data
        run: dvc add data/processed/processed_bike_data

  fetch_weather_data:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install DVC
        run: |
          pip install dvc
          dvc --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

      - name: Fetch weather data
        run: python src/data/fetch_weather_data.py
      - name: Cache weather data
        run: dvc add data/raw/weather

  preprocess_weather_data:
    needs: fetch_weather_data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Preprocess weather data
        run: python src/data/process_weather_data.py
      - name: Cache preprocessed weather data
        run: dvc add data/processed/processed_weather_data

  merge_data:
    needs: [preprocess_bike_data, preprocess_weather_data]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Merge data
        run: python src/data/merge_data.py
      - name: Cache merged data
        run: dvc add data/processed

  commit_and_push:
    needs: merge_data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Commit and push changes
        run: |
          git config --global user.name 'lanaben'
          git config --global user.email 'lanaben@users.noreply.github.com'
          git add .
          git commit -m "Update data and DVC tracking files."
          git push https://lanaben:${{ secrets.IIS_TOKEN }}@github.com/lanaben/ML-engineering.git main
