name: Data Pipeline

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install DVC
        run: |
          pip install dvc
          dvc --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

  fetch_weather_data:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install DVC
        run: |
          pip install dvc
          dvc --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure DVC
        run: |
          dvc remote add origin s3://dvc
          dvc remote modify origin endpointurl https://dagshub.com/lanaben/MBajk-prediction-app.s3
          dvc remote modify origin --local access_key_id 7ddc36c3f8a57b0df9f619f50e6f0a2cf6da5f55 
          dvc remote modify origin --local secret_access_key 7ddc36c3f8a57b0df9f619f50e6f0a2cf6da5f55 

      - name: Pull data with DVC
        run: dvc pull data/raw/weather --force

      - name: Run Python script to generate/update data
        run: python src/data/fetch_weather_data.py

      - name: Add and commit data to DVC
        run: |
          git config --global user.name 'lanaben'
          git config --global user.email 'lanaben@users.noreply.github.com'
          dvc add data
          dvc status
          dvc push
          git add data.dvc
          git commit -m "Update weather data."
          git push https://lanaben:${{ secrets.IIS }}@github.com/lanaben/MBajk-prediction-app.git main
        env:
          IIS: ${{ secrets.IIS }}




