#name: Docker,Render
#
#on:
#  push:
#    paths:
#      - 'src/**'
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.8'
#
#      - name: Install dependencies
#        run: |
#          pip install -r requirements.txt
#
#      - name: Run pytest
#        run: |
#          pytest
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#
#      - name: Build images
#        run: |
#          docker build -t lanaben/backend-bikes .
#          docker build -t lanaben/frontend-bikes ./src/client
#
#      - name: Push to Docker Hub
#        run: |
#          docker push <your-dockerhub-username>/<backend-image-name>
#          docker push <your-dockerhub-username>/<frontend-image-name>
#
#      - name: Deploy to production
#        uses: johnbeynon/render-deploy-action@v0.0.8
#        with:
#          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
#          api-key: ${{ secrets.MY_RENDER_API_KEY }}
#          wait-for-success: true
