name: Fetch Data Workflow

on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch_data.py
      run: python src/data/fetch_data.py

    - name: Commit changes
      run: |
        git config --global user.name 'lanaben'
        git config --global user.email 'lanaben@users.noreply.github.com'
        git commit -am "Automated report"
        git push